import Layout from '../../components/Layout'
import Head from 'next/head'

export default function TeamPage(props) {
  const { id } = props;

  return (
    <Layout>
		<Head>
			<title>TEAM {id}</title>
			<meta name="description" content="Generated by create next app" />
			<link rel="icon" href="/favicon.ico" />
      	</Head>
		<h1>TEAM {id}</h1>
	</Layout>
  );
}

export async function getServerSideProps({ params }) {

  return {
    props: {
      id: params.id,
    },
  };
}
